CREATE ROLE app LOGIN PASSWORD 'app';
CREATE ROLE readonly LOGIN PASSWORD 'readonly';

GRANT CONNECT ON DATABASE db TO app, readonly;

GRANT USAGE ON SCHEMA public TO app, readonly;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
GRANT SELECT, UPDATE, DELETE, INSERT ON ALL TABLES IN SCHEMA public TO app;

ALTER DEFAULT PRIVILEGES FOR ROLE admin IN SCHEMA public GRANT DELETE, UPDATE, INSERT, SELECT ON TABLES TO app;
ALTER DEFAULT PRIVILEGES FOR ROLE admin IN SCHEMA public GRANT SELECT ON TABLES TO readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE admin IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app;