ALTER TABLE profession ADD COLUMN IF NOT EXISTS description_search TSVECTOR;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS skills JSONB;
ALTER TABLE buyers ADD COLUMN IF NOT EXISTS preferences JSONB;
ALTER TABLE pvz ADD COLUMN IF NOT EXISTS coordinates POINT;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS working_hours TSRANGE;
ALTER TABLE category_of_item ADD COLUMN IF NOT EXISTS attributes JSONB;
ALTER TABLE items ADD COLUMN IF NOT EXISTS tags TEXT[];
ALTER TABLE worker_assignments ADD COLUMN IF NOT EXISTS work_period DATERANGE;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS purchase_period TSRANGE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_range TSRANGE;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS review_text TSVECTOR;

CREATE TABLE IF NOT EXISTS delivery_zones (
    zone_id SERIAL PRIMARY KEY,
    pvz_id INT REFERENCES pvz(pvz_id),
    coverage_area POLYGON
);